org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoiYWJkdWxsYS1yYXVmLXBwIiwiYSI6ImNtajVpdndpZDFsbnIzZXNic3h3bmdnZHkifQ.8rnSkvms8mW5alXS7XyKPw
SDK_REGISTRY_TOKEN=sk.eyJ1IjoiYWJkdWxsYS1yYXVmLXBwIiwiYSI6ImNtajVpdndpZDFsbnIzZXNic3h3bmdnZHkifQ.8rnSkvms8mW5alXS7XyKPw
